name: Continuous Integration

on:
  push:
  workflow_dispatch:

jobs:
  execute_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          components: |
            platform-tools
            build-tools;34.0.0
            platforms;android-34
            system-images;android-34;google_apis;x86_64
            emulator

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Appium
        run: |
          npm install -g appium

      - name: Ensure UiAutomator2 Driver is Installed
        run: |
          if ! appium driver list --installed | grep uiautomator2; then
            appium driver install uiautomator2 || true;
          else
            appium driver update uiautomator2 || true;  # Atualiza o driver caso já esteja instalado
          fi

      - name: Install Android SDK system image
        run: |
          sdkmanager --install "system-images;android-34;google_apis;x86_64"

      - name: Create Android Emulator
        run: |
          echo no | avdmanager create avd -n "Pixel_4_XL_API_34" -k "system-images;android-34;google_apis;x86_64" -d pixel_4_xl

      - name: Start Android Emulator
        run: |
          nohup emulator -avd Pixel_4_XL_API_34 -no-window -no-audio -gpu off &
          adb wait-for-device  # Aguarda até que o dispositivo esteja disponível
          adb shell input keyevent 82  # Desbloqueia a tela do emulador

      - name: Start Appium
        run: |
          nohup appium -p 4725 --log-level debug &
          sleep 30  # Aumenta o tempo de espera para garantir que o Appium esteja pronto e o emulador disponível

      - name: Check connected devices
        run: |
          adb devices  # Verifica se o dispositivo está conectado

      - name: Run Robot Framework Tests
        run: |
          robot -d ./reports -v APPIUM_PORT:4725 -v APK_PATH:./yodapp-robot/app/yodapp-beta.apk .

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: reports
